SELECT RCAB.IDINSTPRN AS IDPROCESSO, RCAB.CODEMP, RCAB.CODPARC, RCAB.CODNAT, RCAB.CODCENCUS, RCAB.CODTIPVENDA, PPG.CODTIPTITPAD, CTA.CODCTABCOINT, 4100 AS CODTIPOPER, GETDATE() AS DTNEG, GETDATE()+PPG.PRAZO AS DTVENC,
       SUM(RITENS.VLRTOT) AS VLRDESDOB
FROM AD_REQUISICAOCOMPRAITENS RITENS
         INNER JOIN AD_REQUISICAOCOMPRA RCAB ON RITENS.IDINSTPRN = RCAB.IDINSTPRN
         INNER JOIN TGFPPG PPG ON PPG.CODTIPVENDA = RCAB.CODTIPVENDA
         INNER JOIN TSICTA CTA ON CTA.CODEMP = RCAB.CODEMP
WHERE RITENS.IDINSTPRN = :IDPROCESSO
  AND CTA.CODCTABCOINT = CASE WHEN RCAB.CODEMP = 1 THEN 4 ELSE 7 END
GROUP BY RCAB.IDINSTPRN, RCAB.CODEMP, RCAB.CODPARC, RCAB.CODNAT, RCAB.CODCENCUS, RCAB.CODTIPVENDA, PPG.CODTIPTITPAD, CTA.CODCTABCOINT, PPG.PRAZO