SELECT
    F.NUFIN,
    F.CODTIPTIT,
    T.AD_TIPOPAG,
    F.CODBCO,
    C.CODRELATORIO
FROM TGFFIN F
         INNER JOIN TGFTIT T ON F.CODTIPTIT = T.CODTIPTIT
         INNER JOIN TSIBCO B ON F.CODBCO = B.CODBCO
         INNER JOIN AD_MODIMPPGTO C ON C.CODBCO = B.CODBCO AND C.TIPOPAG = T.AD_TIPOPAG
WHERE
    F.NUFIN = :NUFIN